# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='ip_address',
            field=models.CharField(default='0.0.0.0', max_length=200),
        ),
    ]
